// Generated by CoffeeScript 1.4.0
(function() {
  var Fraction, Monome, Operateur, activer_copier_contenu, activer_copier_symbole, ajouter_membre, changementSens, debug, fracString_to_frac, generate_equation, generate_equation_string, get_focused_id, liste_des_chiffres, liste_des_operateurs, liste_des_signes, liste_des_variables, monomeString_to_array, multiplier_distribuer_membre, multiplier_factoriser_membre, obtenir_la_solution, operation_sur_equation, signes, unique_id,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  unique_id = 1;

  debug = false;

  activer_copier_symbole = "";

  activer_copier_contenu = {};

  liste_des_chiffres = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'];

  liste_des_operateurs = ['+', '-'];

  signes = ['≤', '≤', '≥', '>', '<', '=', '=', '=', '=', '=', '=', '=', '=', '=', '=', '=', '=', '='];

  liste_des_variables = ['x', 'y', 'z', 't'];

  liste_des_signes = ['=', '<', '>', '≤', '≥'];

  changementSens = {
    '=': '=',
    '<': '>',
    '>': '<',
    '≤': '≥',
    '≥': '≤'
  };

  fracString_to_frac = function(value) {
    var d, foo, n, _ref;
    foo = value.split("/");
    switch (foo.length) {
      case 2:
        _ref = [parseInt(foo[0]), parseInt(foo[1])], n = _ref[0], d = _ref[1];
        if ((n != null) && (d != null)) {
          return foo = new Fraction(n, d);
        } else {
          return alert("Erreur : fracString_to_frac, n is " + n + " and d is " + d + " !");
        }
        break;
      case 1:
        n = parseInt(foo[0]);
        if (n != null) {
          return foo = new Fraction(n, 1);
        } else {
          return alert("Erreur : fracString_to_frac, n is " + n + " !");
        }
        break;
      default:
        return alert("Erreur : fracString_to_frac, value is " + value + " !");
    }
  };

  Fraction = (function() {

    function Fraction(numerateur, denominateur) {
      this.numerateur = numerateur;
      this.denominateur = denominateur;
    }

    Fraction.prototype.irreductible = function() {
      var a, b, _ref, _ref1, _ref2, _ref3;
      _ref = [this.numerateur, this.denominateur], a = _ref[0], b = _ref[1];
      while (b !== 0) {
        _ref1 = [b, a % b], a = _ref1[0], b = _ref1[1];
      }
      _ref2 = [this.numerateur / a, this.denominateur / a], this.numerateur = _ref2[0], this.denominateur = _ref2[1];
      if (this.denominateur < 0) {
        _ref3 = [-this.numerateur, -this.denominateur], this.numerateur = _ref3[0], this.denominateur = _ref3[1];
      }
      return this;
    };

    Fraction.prototype.inverse = function() {
      var _ref;
      if (this.numerateur !== 0) {
        _ref = [this.denominateur, this.numerateur], this.numerateur = _ref[0], this.denominateur = _ref[1];
        return this;
      }
    };

    Fraction.prototype.oppose = function() {
      this.numerateur = -this.numerateur;
      return this;
    };

    Fraction.prototype.toString = function() {
      return "" + this.numerateur + "/" + this.denominateur;
    };

    Fraction.prototype.toHtml = function() {
      var html;
      if (this.denominateur === 1) {
        if (this.numerateur < 0) {
          return html = "<span class='moins'>&minus;</span><span class='rationnel'>" + (Math.abs(this.numerateur)) + "</span>";
        } else {
          return html = "<span class='plus'>&plus;</span><span class='rationnel'>" + this.numerateur + "</span>";
        }
      } else {
        if (this.numerateur < 0) {
          return html = "<span class='moins'>&minus;</span><span class='fraction'><span class='top'>" + (Math.abs(this.numerateur)) + "</span><span class='bottom'>" + this.denominateur + "</span></span>";
        } else {
          return html = "<span class='plus'>&plus;</span><span class='fraction'><span class='top'>" + this.numerateur + "</span><span class='bottom'>" + this.denominateur + "</span></span>";
        }
      }
    };

    Fraction.prototype.ajouter = function(fraction) {
      var _ref, _ref1;
      if (this.nominateur !== fraction.denominateur) {
        _ref = [this.numerateur * fraction.denominateur + fraction.numerateur * this.denominateur, this.denominateur * fraction.denominateur], this.numerateur = _ref[0], this.denominateur = _ref[1];
      } else {
        _ref1 = [this.numerateur + fraction.numerateur, this.denominateur], this.numerateur = _ref1[0], this.denominateur = _ref1[1];
      }
      return this;
    };

    Fraction.prototype.multiplier = function(fraction) {
      var _ref;
      _ref = [this.numerateur * fraction.numerateur, this.denominateur * fraction.denominateur], this.numerateur = _ref[0], this.denominateur = _ref[1];
      return this;
    };

    return Fraction;

  })();

  monomeString_to_array = function(s) {
    var foo, pattern_terme;
    if (debug) {
      console.log("monomeString_to_array(" + s + ")");
    }
    pattern_terme = /\([\+\-]*\d+[/\d+]*\)(\w+²{0,1})*/g;
    foo = s.match(pattern_terme);
    if ((foo != null) && foo[0] === s) {
      if (debug) {
        alert("" + s + " match regex:" + pattern_terme);
      }
      foo = s.split(")");
      return foo = foo[1] ? [foo[0].slice(1), foo[1]] : [foo[0].slice(1)];
    } else {
      return alert("Vous devriez effacer l'invite de commande et envisager quelquechose de mieux pondéré...ok !?");
    }
  };

  Monome = (function() {

    function Monome($monome) {
      if ($monome) {
        this.id = "#" + ($monome.attr('id'));
        this.parent_id = "#" + ($(this.id).parent().attr('id'));
        this.side = $(this.id).hasClass("gauche") ? "gauche" : "droite";
        this.fraction = fracString_to_frac($(this.id).attr("data-value"));
        this.type = $(this.id).attr("data-type");
        this.symbol = this.type === "symbol" ? $(this.id).attr("data-symbol") : "";
      } else {
        this.id = "#" + (unique_id++);
      }
    }

    Monome.prototype.update = function() {
      $(this.id).attr("data-value", this.fraction.toString());
      return $(this.id).html(this.html_content());
    };

    Monome.prototype.irreductible = function() {
      this.fraction.irreductible();
      return this.update();
    };

    Monome.prototype.remove = function() {
      return $(this.id).remove();
    };

    Monome.prototype.html_content = function() {
      var html, _ref;
      switch (this.type) {
        case "symbol":
          if ((_ref = this.fraction.numerateur * this.fraction.denominateur) === (-1) || _ref === 1) {
            if (this.fraction.numerateur / this.fraction.denominateur === 1) {
              return html = "<span class='droppable'><span class='plus' >+      </span><span>" + this.symbol + "</span></span>";
            } else {
              return html = "<span class='droppable'><span class='moins'>&minus;</span><span>" + this.symbol + "</span></span>";
            }
          } else {
            return html = "<span class='droppable'>" + (this.fraction.toHtml()) + "<span>" + this.symbol + "</span></span>";
          }
          break;
        default:
          return html = "<span class='droppable'>" + (this.fraction.toHtml()) + "</span>";
      }
    };

    Monome.prototype.toHtml = function() {
      var html;
      return html = "<li id='" + this.id.slice(1) + "' class='monome item' data-value='" + (this.fraction.toString()) + "' data-type='" + this.type + "' data-symbol='" + this.symbol + "'><span class='monome_html'>" + (this.html_content()) + "</span></li>";
    };

    Monome.prototype.insert = function(id, fraction, symbol) {
      var html;
      this.fraction = fraction;
      this.symbol = symbol;
      this.type = this.symbol != null ? "symbol" : "rationnel";
      html = "<li id='" + this.id.slice(1) + "' class='monome item' data-value='" + this.fraction + "' data-type='" + this.type + "' ";
      html += this.symbol != null ? "data-symbol='" + this.symbol + "'></li>" : "></li>";
      $(id).append(html);
      return this.update();
    };

    Monome.prototype.insert_from_string = function(equation_id, monomeString) {
      var fraction, m;
      this.equation_id = equation_id;
      m = monomeString.split(")");
      fraction = fracString_to_frac(m[0].slice(1));
      if (m[1]) {
        return (new Monome()).insert(this.equation_id, fraction, m[1]);
      } else {
        return (new Monome()).insert(this.equation_id, fraction);
      }
    };

    Monome.prototype.ajouter = function(monome) {
      if ((this.type === monome.type) && ((this.type === "rationnel") || (this.symbol === monome.symbol))) {
        this.fraction.ajouter(monome.fraction);
      } else {
        alert("On ne mélange pas symboles & chiffres !");
      }
      return this;
    };

    Monome.prototype.toString = function() {
      var s;
      switch (this.type) {
        case "rationnel":
          return s = "(" + (this.fraction.toString()) + ")";
        default:
          return s = "(" + (this.fraction.toString()) + ")" + this.symbol;
      }
    };

    Monome.prototype.toArray = function() {
      return monomeString_to_array(this.toString());
    };

    return Monome;

  })();

  Operateur = (function() {

    function Operateur(id, symbol, membre) {
      var classe, html;
      this.symbol = symbol;
      classe = {
        "*": "multiplication",
        "+": "addition"
      };
      if (this.symbol != null) {
        this.type = classe[this.symbol];
        this.id = unique_id++;
        html = "<ul id='" + this.id + "' class='operateur " + this.type + " item' data-symbol='" + this.symbol + "'></ul>";
        this.id = "#" + this.id;
        switch ($(id).attr("data-symbol")) {
          case this.symbol:
            $(id).append(html);
            break;
          default:
            $(id).wrap(html);
        }
      } else {
        this.id = id;
        this.symbol = $(this.id).attr("data-symbol");
        this.type = classe[this.symbol];
      }
      this.parent_id = "#" + ($(this.id).parent().attr('id'));
      this.update();
    }

    Operateur.prototype.update = function() {
      return this;
    };

    Operateur.prototype.monomesString_insert = function(membre) {
      var monomeString, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = membre.length; _i < _len; _i++) {
        monomeString = membre[_i];
        _results.push((new Monome()).insert_from_string(this.id, monomeString));
      }
      return _results;
    };

    return Operateur;

  })();

  generate_equation_string = function(n, min, max) {
    var coeff, equation, side, str, toss, _i, _j, _len, _ref;
    if (min == null) {
      min = -10;
    }
    if (max == null) {
      max = 10;
    }
    equation = {};
    equation["signe"] = signes[Math.floor(Math.random() * signes.length)];
    _ref = ["gauche", "droite"];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      side = _ref[_i];
      str = "";
      for (_j = 1; 1 <= n ? _j <= n : _j >= n; 1 <= n ? _j++ : _j--) {
        coeff = Math.floor(Math.random() * (max - min + 1)) + min;
        toss = Math.floor(Math.random() * 2.) - 1;
        str += toss === 0 ? "+(" + coeff + ") " : "+(" + coeff + ")x ";
      }
      equation[side] = str.slice(1);
    }
    return equation = "" + equation['gauche'] + " " + equation['signe'] + " " + equation['droite'];
  };

  generate_equation = function(unknown, factor_length, depth, min, max) {
    var alphabet, coeff, html, i, id, j, membre, monomeString, op, signe, toss, _base, _i, _j, _k, _ref, _ref1, _ref2, _ref3;
    if (min == null) {
      min = -10;
    }
    if (max == null) {
      max = 10;
    }
    id = unique_id++;
    signe = signes[Math.floor(Math.random() * signes.length)];
    html = "<div id='equation_" + id + "' class='equation' >\n    <button id='deleteButton_" + id + "' class='deleteButton' title='Supprimer cette équation'>x</button>    \n    <p id='solution_" + id + "'></p>\n    <ul id='fake'></ul>\n    <span id='signe_" + id + "' class='signe'>" + signe + "</span>\n</div>";
    $("#equations_div").append(html);
    $("#fake").remove();
    $("#equations_div").sortable();
    if ((_ref = (_base = Array.prototype).shuffle) == null) {
      _base.shuffle = function() {};
    }
    if (this.length > 1) {
      for (i = _i = _ref1 = this.length - 1; _ref1 <= 1 ? _i <= 1 : _i >= 1; i = _ref1 <= 1 ? ++_i : --_i) {
        j = Math.floor(Math.random() * (i + 1));
        _ref2 = [this[j], this[i]], this[i] = _ref2[0], this[j] = _ref2[1];
        return this;
      }
    }
    alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
    op = new Operateur("#fake", "+");
    membre = [];
    for (i = _j = 1; 1 <= unknown ? _j <= unknown : _j >= unknown; i = 1 <= unknown ? ++_j : --_j) {
      monomeString = "";
      for (_k = 1; 1 <= factor_length ? _k <= factor_length : _k >= factor_length; 1 <= factor_length ? _k++ : _k--) {
        _ref3 = [Math.floor(Math.random() * (max - min + 1)) + min, Math.floor(Math.random() * 2.) - 1], coeff = _ref3[0], toss = _ref3[1];
        monomeString += toss === 0 ? "(" + coeff + ")" : "(" + coeff + ")" + alphabet[i];
      }
      membre.push(monomeString);
    }
    alert(membre);
    return op.monomesString_insert(membre);
  };

  obtenir_la_solution = function(id) {
    var $li_droite, $li_gauche, s, signe, solution, _ref;
    if ($("#equation_" + id + " > ul.membre.gauche > li").length === 1 && $("#equation_" + id + " > ul.membre.droite > li").length === 1) {
      $li_gauche = $("#equation_" + id + " > ul.membre.gauche > li");
      $li_droite = $("#equation_" + id + " > ul.membre.droite > li");
      if ($li_gauche.attr("data-symbol") && !$li_droite.attr("data-symbol")) {
        if ($li_gauche.attr("data-value") === "1/1" || $li_gauche.attr("data-value") === "1") {
          _ref = [$("#signe_" + id).text(), fracString_to_frac($li_droite.attr("data-value")).irreductible().toHtml()], signe = _ref[0], s = _ref[1];
          switch (signe) {
            case "=":
              solution = "S = {" + s + "}";
              break;
            case ">":
              solution = "S = ]" + s + " ; +∞ [";
              break;
            case "≥":
              solution = "S = [" + s + " ; +∞ [";
              break;
            case "<":
              solution = "S = ] -∞ ; " + s + "]";
              break;
            case "≤":
              solution = "S = ] -∞ ; " + s + "]";
          }
          return $("#solution_" + id).html(solution);
        } else {
          return alert("On ne peut pas encore lire la solution ! il faut que le coefficient _ l'inconnue soit 1.");
        }
      } else {
        return alert("On ne peut pas encore lire la solution ! il faut une l'inconnue à gauche et une valeur à droite.");
      }
    } else {
      return alert("On ne peut pas encore lire la solution ! il faut un seul terme à gauche et un seul terme à droite.");
    }
  };

  ajouter_membre = function(string) {
    var id;
    id = get_focused_id();
    if (id) {
      return $("#equation_" + id + " > .operateur").each(function() {
        var operateur;
        return (operateur = new Operateur("#" + ($(this).attr('id')), "+")).monomesString_insert(string);
      });
    }
  };

  multiplier_distribuer_membre = function(facteur) {
    var id;
    id = get_focused_id();
    if (id && facteur.denominateur) {
      return $("#equation_" + id + " > ul > li.monome").each(function() {
        var m;
        m = new Monome($(this));
        m.fraction.multiplier(facteur);
        return m.update();
      });
    }
  };

  multiplier_factoriser_membre = function(string) {
    var id;
    id = get_focused_id();
    if (id) {
      return $("#equation_" + id + " > .operateur").each(function() {
        var operateur;
        return (operateur = new Operateur("#" + ($(this).attr('id')), "*")).monomesString_insert(string);
      });
    }
  };

  get_focused_id = function() {
    var id;
    return id = $(".focus").attr("id") ? $(".focus").attr("id").split("_")[1] : alert("Selectionner une équation !");
  };

  operation_sur_equation = function(mode, id) {
    var array, _ref;
    if (_ref = $("#equation_string").val().slice(-1), __indexOf.call(liste_des_chiffres, _ref) >= 0) {
      $("#equation_string").val("" + ($('#equation_string').val()) + ")");
    }
    id = get_focused_id();
    array = monomeString_to_array($("#equation_string").val());
    if ((id != null) && (array != null)) {
      switch (mode) {
        case "diviser":
          return multiplier_distribuer_membre(fracString_to_frac(array[0], array[1]));
        case "multiplier_factoriser":
          return multiplier_factoriser_membre($("#equation_string").val().split("+"));
        case "multiplier_distribuer":
          return multiplier_distribuer_membre(fracString_to_frac(array[0], array[1]));
        case "retrancher":
          return ajouter_membre((fracString_to_frac(array[0])).oppose(), array[1]);
        case "ajouter":
          return ajouter_membre($("#equation_string").val().split("+"));
      }
    } else {
      return alert("Poids surement mal formé !");
    }
  };

  $(function() {
    var addCurve, board, char, clearAll, doIt, monome_irreductible, once, p, plot, _i, _j, _len, _len1, _ref;
    $("#generer_equation_complexe").on("click", function() {
      return generate_equation(2, 2, 2, -10, 10);
    });
    $('body').on("click", "ul", function(event) {
      if (($(this).children().length === 1) && ($(this).children("ul").length === 1)) {
        $(this).contents().unwrap();
      }
      if (($(this).children().length === 1) && (!$(this).parent().hasClass("equation"))) {
        return $(this).contents().unwrap();
      }
    });
    (once = function() {
      $("#toggle_help").on("click", function() {
        return $("#help, #aside, #footer").toggle();
      });
      return $("#help, #aside, #footer").toggle();
    })();
    $(".operateur").on("click", function() {
      if (($(this).children().length < 2) || ($(this).attr('data-symbol') === $(this).parent().attr('data-symbol'))) {
        return $(this).unwrap();
      }
    });
    $("#generer_equation").on("click", function() {
      return $("#equation_string").val(generate_equation_string(Math.floor(10 * Math.random()) + 1));
    });
    $("#inserer_equation").on("click", function() {
      var html, id, match, mdd, mdg, operateur, pattern_equation, s, signe, _ref, _ref1;
      s = $("#equation_string").val();
      if ((_ref = s.slice(-1), __indexOf.call(liste_des_chiffres, _ref) >= 0)) {
        $("#equation_string").val("" + s + ")");
      }
      s = $("#equation_string").val().replace(/\s+/g, '');
      pattern_equation = /((?:\([\+\-]*\d+[\/\d+]*\)(?:\w+²?)*)(?:\+(?:\([\+\-]*\d+[\/\d+]*\)(?:\w+²?)*))*)([<≤=≥>])((?:\([\+\-]*\d+[\/\d+]*\)(?:\w+²?)*)(?:\+(?:\([\+\-]*\d+[\/\d+]*\)(?:\w+²?)*))*)/g;
      switch ((match = pattern_equation.exec(s)).length) {
        case 0:
          return alert("Vérifier que l'équation est correctement formatée");
        default:
          _ref1 = [match[2], match[1].split("+"), match[3].split("+"), unique_id++], signe = _ref1[0], mdg = _ref1[1], mdd = _ref1[2], id = _ref1[3];
          html = "<div id='equation_" + id + "' class='equation' >\n    <button id='deleteButton_" + id + "' class='deleteButton' title='Supprimer cette équation'>x</button>    \n    <p id='solution_" + id + "'></p>\n    <ul id='fakeg'></ul>\n    <span id='signe_" + id + "' class='signe'>" + signe + "</span>\n    <ul id='faked'></ul>\n</div>";
          $("#equations_div").append(html);
          (operateur = new Operateur("#fakeg", "+")).monomesString_insert(mdg);
          (operateur = new Operateur("#faked", "+")).monomesString_insert(mdd);
          $("#fakeg, #faked").remove();
          $("#equations_div").sortable();
          return $("#equation_" + id).trigger("click");
      }
    });
    $("#effacer_equation_string").on("click", function() {
      return $("#equation_string").val("");
    });
    $("body").on("click", ".selectAllButton", function(event) {
      var id;
      if (id = get_focused_id()) {
        return $("#equation_" + id + ".focus ul > .monome").addClass("selected");
      }
    });
    monome_irreductible = function($monome) {
      var m;
      return (m = new Monome($monome)).irreductible();
    };
    $("body").on("dblclick", ".monome", function() {
      return monome_irreductible($(this));
    });
    $("body").on("click", ".simplifier_les_monomes", function() {
      var id;
      if (id = get_focused_id()) {
        return $("#equation_" + id + " > ul > li.selected").each(function() {
          return monome_irreductible($(this));
        });
      }
    });
    $('body').on("mousedown", "li", function(event) {
      var m, op, _ref, _ref1;
      m = new Monome($(this));
      op = new Operateur(m.parent_id);
      switch (op.type) {
        case "addition":
          if (m.fraction.numerateur === 0) {
            switch ($("" + m.id).siblings().length) {
              case 0:
                _ref = ["rationnel", 0], m.type = _ref[0], m.fraction.numerateur = _ref[1];
                m.update();
                break;
              default:
                $("" + m.id).remove();
            }
          }
          break;
        case "multiplication":
          if ((m.type === "rationnel") && (m.fraction.numerateur / m.fraction.denominateur === 1)) {
            switch ($("" + m.id).siblings().length) {
              case 0:
                _ref1 = ["rationnel", 1], m.type = _ref1[0], m.fraction.numerateur = _ref1[1];
                m.update();
                break;
              default:
                $("" + m.id).remove();
            }
          }
      }
      $(op.id).sortable({
        connectWith: "." + op.type,
        revert: true,
        receive: function(event, ui) {
          if (!((("" + op.id) === ui.sender.parent().attr("id")) || (("" + op.parent_id) === ui.sender.attr("id")))) {
            return ui.sender.sortable("cancel");
          } else {
            if (ui.sender.children("ul, li").length === 0) {
              switch (op.type) {
                case "addition":
                  return (new Monome()).insert(ui.sender.attr('id'), new Fraction(0, 1));
                case "multiplication":
                  return (new Monome()).insert(ui.sender.attr('id'), new Fraction(1, 1));
              }
            }
          }
        }
      });
      $(m.id).siblings("li").droppable({
        accept: "" + m.id,
        hoverClass: "ui-state-hover",
        activeClass: "ui-state-highlight",
        drop: function(event, ui) {
          var m1, m2, op2;
          m1 = new Monome($(m.id));
          m2 = new Monome($(this));
          if ($(m.parent_id).hasClass("addition")) {
            if (m1.type === m2.type) {
              if ((m1.type === "rationnel") || (m1.symbol === m2.symbol)) {
                m2.fraction.ajouter(m1.fraction);
                m2.update();
                return m1.remove();
              } else {
                return alert("On ne mélange pas symboles & chiffres !");
              }
            }
          } else if ($(m.parent_id).hasClass("multiplication")) {
            if ($(m2.id).hasClass("monome")) {
              m2.fraction.multiplier(m1.fraction);
              m2.update();
              m1.fraction = new Fraction(1, 1);
              return m1.update();
            } else {
              return op2 = new Operateur(m.id, op.symbol).monomesString_insert(m2.toString);
            }
          }
        }
      });
      $(m.id).siblings("ul").droppable({
        accept: "" + m.id,
        hoverClass: "ui-state-hover",
        activeClass: "ui-state-highlight",
        drop: function(event, ui) {
          var op2, op3;
          op2 = new Operateur("#" + ($(this).attr('id')));
          if (op2.type === op.type) {
            return $(op2.id).append($(m.id));
          } else if (op.type === "addition" && op2.type === "multiplication") {
            op3 = new Operateur(op2.id, op.symbol).monomesString_insert([m.toString()]);
            return $(m.id).remove();
          } else if (op.type === "multiplication" && op2.type === "addition") {
            $(op2.id).children("ul, li").each(function() {
              return op3 = new Operateur("#" + ($(this).attr('id')), op.symbol).monomesString_insert([m.toString()]);
            });
            return $(m.id).remove();
          }
        }
      });
      return $("#equation_string").val(m.toString());
    });
    $("body").on("click", ".sommationMonome", function() {
      var id;
      if (id = get_focused_id()) {
        return $(".operateur.addition").each(function() {
          var coeffs, fraction, m, op_id, selected, symbol;
          selected = $(this).find(".selected");
          coeffs = {};
          coeffs["rationnel"] = new Fraction(0, 1);
          op_id = "#" + ($(this).attr('id'));
          $(selected).each(function() {
            var m;
            m = new Monome($(this));
            switch (m.type) {
              case "symbol":
                return coeffs[m.symbol] = coeffs[m.symbol] != null ? m.fraction.ajouter(coeffs[m.symbol]) : m.fraction;
              case "rationnel":
                return coeffs["rationnel"] = m.fraction.ajouter(coeffs["rationnel"]);
            }
          });
          for (symbol in coeffs) {
            fraction = coeffs[symbol];
            m = new Monome();
            switch (symbol) {
              case "rationnel":
                m.insert(op_id, fraction);
                break;
              default:
                m.insert(op_id, fraction, symbol);
            }
          }
          return $(selected).remove();
        });
      }
    });
    $("body").on("click", ".coller", function() {
      var check_substitute, id;
      check_substitute = function(id) {
        var fraction1;
        if ($(this).attr("data-symbol") === activer_copier_symbole) {
          fraction1 = fracString_to_frac($(this).attr("data-value"));
          return activer_copier_contenu.each(function() {
            var fraction2, type, value;
            fraction2 = fracString_to_frac($(this).attr("data-value"));
            value = fraction1.multiplier(fraction2);
            type = $(this).attr("data-type");
            if (type === "rationnel") {
              (new Monome()).insert(id, side, value);
            } else {
              (new Monome()).insert(id, side, value, "" + symbol);
            }
            return $(this).hide("easeInElastic", function() {
              return $(this).remove();
            });
          });
        }
      };
      id = get_focused_id();
      return $("#equation_" + id).find("li").each(function() {
        return check_substitute(id);
      });
    });
    board = JXG.JSXGraph.initBoard('box', {
      boundingbox: [-5, 8, 8, -5],
      axis: true
    });
    addCurve = function(board, func, atts) {
      var f;
      return f = board.create('functiongraph', [func], atts);
    };
    plot = function(func, atts) {
      if (atts === null) {
        return addCurve(board, func, {
          strokewidth: 2
        });
      } else {
        return addCurve(board, func, atts);
      }
    };
    p = board.create('point', [1, 1], {
      style: 6,
      name: 'p'
    });
    clearAll = function() {
      JXG.JSXGraph.freeBoard(board);
      board = JXG.JSXGraph.initBoard('box', {
        boundingbox: [-5, 8, 8, -5],
        axis: true
      });
      return p = board.create('point', [3, -4], {
        style: 6,
        name: 'p'
      });
    };
    doIt = function() {
      var f, g, s;
      s = $("#equation_string").val();
      s = s.replace(/[\(]/g, "").replace(/\)/g, "").replace(/\x/g, "*x").replace(/\+\-/, "-");
      f = s.split(/[=<>≤≥]/)[0];
      f = "function f(x){ return " + f + ";};plot(f);";
      g = s.split(/[=<>≤≥]/)[1];
      g = "function g(x){ return " + g + ";};plot(g);";
      return eval(f + g);
    };
    $("#plotter").on("click", function() {
      return doIt();
    });
    $("#eraser").on("click", function() {
      return clearAll();
    });
    $("#toggle-box").on("click", function() {
      return $("#box, #close-box").toggle();
    });
    $("#plotter").on("click", function() {
      return $("#box, #close-box").show();
    });
    _ref = liste_des_variables.concat(liste_des_operateurs.concat(["/"].concat(liste_des_signes)));
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      char = _ref[_i];
      $("#equation_panel").append("<button id='var_" + char + "' class='panel_touch'>" + char + "</button>");
    }
    for (_j = 0, _len1 = liste_des_chiffres.length; _j < _len1; _j++) {
      char = liste_des_chiffres[_j];
      $("#equation_panel").append("<button id='var_" + char + "' class='panel_touch'>" + char + "</button>");
    }
    $("button").button();
    $('body').on("click", ".panel_touch", function() {
      var caractere_precedent, saisie, _ref1;
      _ref1 = [$(this).attr("id").split("_")[1], $("#equation_string").val()], char = _ref1[0], saisie = _ref1[1];
      caractere_precedent = saisie.length > 0 ? saisie.slice(-1) : '';
      if (char === '←') {
        saisie = saisie.length < 2 ? "" : saisie.slice(0, +(saisie.length - 2) + 1 || 9e9);
      } else {
        if (caractere_precedent === '') {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            saisie += (char === '-' ? "(-" : "(");
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            saisie += "(" + char;
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            saisie += "(1)" + char;
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            alert("il faut un membre à gauche !");
          } else if (char === '/') {
            alert("Impossible de commencer par ça !");
          }
        } else if (__indexOf.call(liste_des_operateurs, caractere_precedent) >= 0 || caractere_precedent === '(') {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            if (caractere_precedent !== '-') {
              saisie += (char === '-' ? "" + char : alert("Deux opérateurs d'affilés ?"));
            } else {
              alert("Deux fois le même opérateur ?");
            }
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            saisie += "" + char;
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            saisie += "1)" + char;
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            alert("Effacer le dernier signe !");
          } else if (char === '/') {
            alert("Impossible d'ecrire " + caractere_precedent + char + " !");
          }
        } else if (__indexOf.call(liste_des_chiffres, caractere_precedent) >= 0) {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            saisie += (char === '-' ? ")+(-" : ")" + char + "(");
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            saisie += "" + char;
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            saisie += ")" + char;
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            saisie += ")" + char;
          } else if (char === '/') {
            saisie += "" + char;
          }
        } else if (__indexOf.call(liste_des_variables, caractere_precedent) >= 0) {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            saisie += (char === '-' ? "+(-" : "" + char + "(");
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            alert("Les coefficients se placent devant les variables !");
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            saisie += "" + char;
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            saisie += "" + char;
          } else if (char === '/') {
            alert("Impossible d'ecrire " + caractere_precedent + char + " !");
          }
        } else if (__indexOf.call(liste_des_signes, caractere_precedent) >= 0) {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            saisie += (char === '-' ? "(-" : "(");
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            saisie += "(" + char;
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            saisie += "(1)" + char;
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            alert("_ux signes d'affilés");
          } else if (char === '/') {
            alert("Impossible d'ecrire " + caractere_precedent + char + " !");
          }
        } else if (caractere_precedent === '/') {
          if (__indexOf.call(liste_des_operateurs, char) >= 0) {
            alert("Impossible d'ecrire " + caractere_precedent + char + " !");
          } else if (__indexOf.call(liste_des_chiffres, char) >= 0) {
            saisie += "" + char;
          } else if (__indexOf.call(liste_des_variables, char) >= 0) {
            alert("Et la fraction ?");
          } else if (__indexOf.call(liste_des_signes, char) >= 0) {
            alert("Et la fraction ?");
          } else if (char === '/') {
            alert("Ca y est déjà !");
          }
        } else {
          saisie += "" + char;
        }
      }
      return $("#equation_string").val(saisie);
    });
    $("body").on("click", ".obtenirSolution", function() {
      var id;
      if (id = get_focused_id()) {
        return obtenir_la_solution(id);
      }
    });
    $("body").on("click", ".multiplier_distribuer", function() {
      return operation_sur_equation("multiplier_distribuer");
    });
    $("body").on("click", ".multiplier_factoriser", function() {
      return operation_sur_equation("multiplier_factoriser");
    });
    $("body").on("click", ".diviser", function() {
      return operation_sur_equation("diviser");
    });
    $("body").on("click", ".ajouter", function() {
      return operation_sur_equation("ajouter");
    });
    $("body").on("click", ".retrancher", function() {
      return operation_sur_equation("retrancher");
    });
    $('body').on("click", ".equation", function() {
      $(".focus").toggleClass("focus");
      return $("#equation_panel").show().appendTo($(this).toggleClass("focus"));
    });
    $("body").on("click", ".copier", function() {
      var id;
      id = get_focused_id();
      activer_copier_symbole = $("#equation_" + id + " > ul.membre.gauche > li").attr("data-symbol");
      activer_copier_contenu = $("#equation_" + id + " > ul.membre.droite > li");
      return alert("symbole copié : " + activer_copier_symbole);
    });
    return $("body").on("click", ".deleteButton", function(event) {
      event.stopPropagation();
      $("body").append($("#equation_panel"));
      return $(this).parent().hide('easeInElastic', function() {
        return $(this).remove();
      });
    });
  });

}).call(this);
